[project]
name = "trustpartners-chatbot"
version = "0.1.0"
description = "Chatbot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.4.1",
    "fastapi>=0.128.4",
    "openai>=2.17.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]
